version: '3'

services:
  database:
    image: 'postgres:latest'
    ports:
      - 5432:5432
    networks:
      - postgres-network
    volumes:
      - db-data:/var/lib/postgresql/data/
    env_file:
      - stack.env
  backend:
    image: 'todo-app-backend-golang:latest'
    depends_on:
      - database
    networks:
      - postgres-network
      - bridge
    ports:
      - 8080:8080
    links:
      - database
    environment:
      - SERVER_PORT=8080
      - POSTGRES_ADDRESS=database:5432/postgres
    env_file:
      - stack.env

volumes:
  db-data:

networks: 
  postgres-network:
    driver: bridge
    external: false
  bridge:
    driver: bridge
